### ISSUE TITLE
maven-noopenjdk tap not updating

### ISSUE THREAD

**Issue by thyzzv** [jcolson/homebrew-taps#1]
Hi.
I am using your excellent maven-noopenjdk tap but since 3.8.2 it will not update with the following error
```
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "maven-noopenjdk_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/maven-noopenjdk/manifests/3.8.2
```

**Comment by jcolson** [comment]
What os and architecture are you running on, for reference?

**Comment by thyzzv** [comment]
Thanks for looking into it.

![image](https://user-images.githubusercontent.com/2563953/130802369-61a8e455-94d6-4b62-ab33-bdce2998668c.png)

**Comment by jcolson** [comment]
this should be fixed now, thanks for the report!  cheers

**Comment by thyzzv** [comment]
Thnx!!
